import { useEffect, useRef, useState } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'

// Hermanus Golf Club location verified against public course listings.
const HERMANUS = [-34.410207, 19.258646] as [number, number]

export function CourseMap({ holeNumber }: { holeNumber: number }) {
  const el = useRef<HTMLDivElement>(null); const map = useRef<L.Map | null>(null); const marker = useRef<L.CircleMarker | null>(null); const target = useRef<L.Marker | null>(null); const watch = useRef<number | null>(null); const position = useRef<L.LatLng | null>(null); const path = useRef<L.Polyline | null>(null); const points = useRef<L.LatLng[]>([])
  const [status, setStatus] = useState('Tap the map to choose a target'); const [accuracy, setAccuracy] = useState<number>(); const [distance, setDistance] = useState<number>(); const [tracking, setTracking] = useState(false)
  useEffect(() => { if (!el.current) return; map.current = L.map(el.current, { zoomControl: false }).setView(HERMANUS, 17); L.control.zoom({ position: 'bottomright' }).addTo(map.current); L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { attribution: 'Imagery © Esri' }).addTo(map.current); const courseBounds: L.LatLngBoundsExpression = [[-34.4148, 19.251], [-34.405, 19.267]]; L.imageOverlay('/golf-tracker/hermanus-course-layout.png', courseBounds, { opacity: 0.68, interactive: false }).addTo(map.current); map.current.fitBounds(courseBounds, { padding: [8, 8] }); map.current.on('click', (event: L.LeafletMouseEvent) => { target.current?.remove(); target.current = L.marker(event.latlng).addTo(map.current!).bindTooltip('Target', { permanent: true, direction: 'top' }); setDistance(position.current ? Math.round(position.current.distanceTo(event.latlng)) : undefined); setStatus(position.current ? 'Target selected' : 'Target selected · locate yourself for distance') }); return () => { if (watch.current !== null) navigator.geolocation?.clearWatch(watch.current); map.current?.remove() } }, [])
  useEffect(() => { target.current?.remove(); target.current = null; setDistance(undefined); setStatus(`Hole ${holeNumber} · tap the map to choose a target`) }, [holeNumber])
  const receive = (p: GeolocationPosition) => { const point = L.latLng(p.coords.latitude, p.coords.longitude); position.current = point; setAccuracy(Math.round(p.coords.accuracy)); marker.current?.setLatLng(point); if (!marker.current) marker.current = L.circleMarker(point, { radius: 8, color: '#b7cf52', fillColor: '#183c2c', fillOpacity: 1, weight: 3 }).addTo(map.current!); if (tracking) { points.current.push(point); path.current?.setLatLngs(points.current) }; if (target.current) setDistance(Math.round(point.distanceTo(target.current.getLatLng()))) }
  const locate = () => { if (!navigator.geolocation) return setStatus('GPS is not available on this device'); setStatus('Waiting for GPS…'); navigator.geolocation.getCurrentPosition((p) => { receive(p); map.current?.setView([p.coords.latitude, p.coords.longitude], 18); setStatus('GPS locked · tap the map for a distance') }, () => setStatus('Location permission was denied'), { enableHighAccuracy: true, maximumAge: 5000, timeout: 15000 }) }
  const toggle = () => { if (tracking) { if (watch.current !== null) navigator.geolocation.clearWatch(watch.current); watch.current = null; setTracking(false); setStatus('Track saved for this hole'); return }; if (!navigator.geolocation) return setStatus('GPS is not available on this device'); points.current = []; path.current?.remove(); path.current = L.polyline([], { color: '#b7cf52', weight: 4 }).addTo(map.current!); setTracking(true); setStatus('Tracking your position…'); watch.current = navigator.geolocation.watchPosition(receive, () => setStatus('Unable to read GPS'), { enableHighAccuracy: true, maximumAge: 3000, timeout: 15000 }) }
  return <section className="course-map-card"><div ref={el} className="course-map" /><div className="map-toolbar"><div><strong>{distance ? `${distance}m to target` : status}</strong><small>{accuracy ? `GPS ±${accuracy}m · tap any point to measure` : 'Locate yourself, then tap a bunker, green, or layup point.'}</small></div><div className="map-actions"><button className="text-button" onClick={locate}>Locate me</button><button className={tracking ? 'text-button tracking' : 'primary-button'} onClick={toggle}>{tracking ? 'Stop track' : 'Track hole'}</button></div></div></section>
}
